### ISSUE TITLE
path.join 改为 path.resolve 呗(´・ω・)ﾉ

### ISSUE THREAD

**Issue by dragon8github** [rat1991/actflow#1]
在 window10 下使用gulp dev，输出这种路径
![image](https://user-images.githubusercontent.com/13919724/35193397-cfc5cb0c-fedc-11e7-858e-c3694207426d.png)

我也看不出问题，后来索性把path.join 改为熟悉的path.resolve才可以。
![image](https://user-images.githubusercontent.com/13919724/35193406-f0d7af22-fedc-11e7-8a33-7bd0b936798f.png)

可能你开发环境是mac，回头我也试试mac的情况。

**Comment by ratup-top** [comment]
之前一直在盘根目录下运行，没考虑到将项目clone到其他文件夹下会引起找不到项目路径，目前已经修复！
